version: "2"
services:
    db:
        volumes:
            - roadiz-db-sync:/var/lib/mysql:nocopy # nocopy is important
    php:
        volumes:
            - roadiz-php-sync:/var/www/html:nocopy #  nocopy is important
    solr:
        volumes:
            - roadiz-solr-sync:/opt/solr/server/solr/mycores:nocopy #  nocopy is important

volumes:
    roadiz-db-sync:
        external:
            name: "${SYNC_NAME}-db-sync"
    roadiz-php-sync:
        external:
            name: "${SYNC_NAME}-php-sync"
    roadiz-solr-sync:
        external:
            name: "${SYNC_NAME}-solr-sync"
