---
appNamespace: "chooseAnUniqueNameForYourApp"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: ""
    password: ""
    dbname: ""
    charset: 'utf8'
    options:
        1002: "SET NAMES 'UTF8'"
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will try to detect best cache driver available
cacheDriver:
    type: ~
    host: ~
    port: ~
security:
    secret: "change#this#secret#very#important"
mailer:
    type: ~
    host: "localhost"
    port: 25
    encryption: false
    username: ""
    password: ""
# Doctrine entities search paths
# Append yours here if you want to create custom
# entities in your theme. Path must be relative to
# root dir (app/)
entities:
    - "../vendor/roadiz/roadiz/src/Roadiz/Core/Entities"
    - "../vendor/roadiz/roadiz/src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
additionalServiceProviders: []
additionalCommands: []
# Image intervention and Intervention Request
# settings for generating image on the fly
assetsProcessing:
    # gd or imagick (gd does not support TIFF and PSD formats)
    driver: gd
    defaultQuality: 90
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: 1920
    jpegoptimPath: ~
    pngquantPath: ~
    subscribers: []
